# Generated by Django 2.1.5 on 2019-03-01 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Categorias'),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Imagenes'),
        ),
    ]
