# Generated by Django 2.1.5 on 2019-03-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190228_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
