# Generated by Django 2.1.5 on 2019-02-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190217_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Imagenes'),
        ),
    ]
